### PR TITLE
Feature/deleting many to many relationships

### PR DESCRIPTION
**Pull request by Jhnbrn90**
A possible approach to allow the deletion of old pivot table entries, having a "deleted_at" column. 

Addressing issue #26

### CODE REVIEW

**Comment by josecanhelp** [comment]
@Jhnbrn90 I really like the approach here. Getting the `deleted_at` row instead of checking against an Eloquent model's bootSoftDeletes method was a good solution to the problem. 

After chatting with @imjohnbon about this PR, the only thing that doesn't sit well with us is the addition of the `pivot_tables` array in the quicksand config file and the duplicated logic in `src/DeleteOldSoftDeletes.php`. 

It would be nice to allow the user to enter both models and pivot tables into a single array in the config file. 

In the logic we could check if the array key is a model by using `is_subclass_of`. If it is a model, find the table name and continue to check the `deleted_at` column as you did in this PR.

If the array key is a string, we can assume it is a pivot table name and continue with the logic you included in this PR.

This way, we only need one method in `src/DeleteOldSoftDeletes.php` that manages force deleting rows in both model related tables and pivot tables.

Does this make sense? We'd love to hear your feedback and we really appreciate your PR. It sparked some good ideas.

**Comment by Jhnbrn90** [comment]
Hi @josecanhelp and @imjohnbon 

Thanks for the kind words! 😄

The approach you desire certainly makes sense and I've tried my best to implement that in the most recent commits to this PR. 

Please let me know if this addressed the problem adequately.

**Comment by josecanhelp** [comment]
Thanks for this @Jhnbrn90! We're going to make a few minor adjustments, but overall this was exactly what we were going for. Cheers! 🍻

**Comment by Jhnbrn90** [comment]
Glad I could be of help. You’re welcome! 👍😃

**Pull request merged**
