### PR TITLE
Add Laravel 5.6 Support

### PR DESCRIPTION
**Pull request by hanspagel**
I added 5.6 to the requirements. :)

### CODE REVIEW

**Comment by mattstauffer** [comment]
@hanspagel Thanks so much! We had it on our list today but haven't gotten to it yet.

By chance, have you tested it on 5.6 and it all worked OK?

Thanks!

**Comment by hanspagel** [comment]
To be honest it's my first pull request ever and I couldn't manage to require my fork. I'll give it another try later or tomorrow.

**Comment by mattstauffer** [comment]
@hanspagel HEYYY congrats man! I'll take a look as soon as I can, and if I can write up how to test it I'll be sure to do that. We'll work with you to get this PR merged for sure. Thank you!!

**Comment by hanspagel** [comment]
Thanks for your welcoming reply, @mattstauffer!

Okay, I'm sure I'm doing this wrong, but that's what I tried: I set the Laravel version in `composer.json` to 5.6 and updated the other dependencies. I updated the test to work with the newer version of PHPUnit. The good news: 3 of 4 tests are successful. The bad news: 1 is failing.

qwrf5pd3zi

I'll try to dig into this error.

**Comment by hanspagel** [comment]
Okay, Taylor renamed `Illuminate\Log\Writer` (which is used in the test) to `Illuminate\Log\Logger` (Source: https://github.com/laravel/framework/pull/22635). I tried to rename it too, but that's not enough.

    1) QuicksandDeleteTest::test_it_logs_if_deleted_entries
    Illuminate\Contracts\Container\BindingResolutionException: Target [Psr\Log\LoggerInterface] is not instantiable.

I don't know how to continue, sorry. :(

**Comment by hanspagel** [comment]
hey @mattstauffer could you point me in the right direction? :)

**Comment by mattstauffer** [comment]
@hanspagel Thanks for following up! Sorry for the delay. Tighten is all in the same physical location over the next few days so I want to set aside a little bit of time to address some of these issues. I promise I'm going to set a reminder for me to dig into this one in the next day or two. Thanks for your patience and this reminder!

**Comment by josecanhelp** [comment]
@hanspagel I submitted a [Pull Request](https://github.com/hanspagel/quicksand/pull/1) with some notes to your branch. Let us know if you have any questions. Once you pull those changes in, we should be good to merge this.

**Comment by hanspagel** [comment]
Nice! Everything back to green. 👍

**Pull request merged**
