### PR TITLE
update composer.json to laravel 5.7

### PR DESCRIPTION
**Pull request by scottgrayson**

### CODE REVIEW

**Comment by rickyjohnston** [comment]
Any word on this one being merged yet? Would be very nice to upgrade. 😉

**Comment by imjohnbon** [comment]
@scottgrayson Thank you for the PR!

@rickyjohnston I'm one of the maintainers on this project along with @josecanhelp. We are going to take a look at this shortly. We should have an update for you soon! Thanks for the nudge. 😃

**Comment by rickyjohnston** [comment]
@imjohnbon nice one! Thanks for that and for everything that you guys at Tighten do for the community.

@scottgrayson you rock.

**Comment by imjohnbon** [comment]
@rickyjohnston Thank you! We just tagged version `2.0.0` for use in Laravel 5.7.

@scottgrayson Thanks again for your PR.

**Pull request merged**
