### PR TITLE
Added Laravel 5.5 support

### PR DESCRIPTION
**Pull request by KillermenBE**

### CODE REVIEW

**Comment by KillermenBE** [comment]
Anyone?

**Comment by mattstauffer** [comment]
Thanks for this PR! Sorry, I missed this in the midst of hurricane prep. I'll take a look today. Thank you!

**Comment by tomschlick** [comment]
+1 for this

**Comment by mattstauffer** [comment]
@tomschlick @killermenbe I'm sorry for the delay. I need to spin up a 5.5 app and test the package in it so I can make sure it works. I will try to do that today if af all possible so I can merge this in.

**Comment by mattstauffer** [comment]
Tested it on a sample app and didn't see any issues. Thanks!

**Comment by mattstauffer** [comment]
@KillermenBE @tomschlick https://github.com/tightenco/quicksand/releases/tag/v0.2.3 Thanks!

**Pull request merged**
